// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: protobufs/auth.proto

package protobufsconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	http "net/http"
	protobufs "ravirajdarisi/auth-service/api/protobufs"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "auth.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceSignupWithPhoneNumberProcedure is the fully-qualified name of the AuthService's
	// SignupWithPhoneNumber RPC.
	AuthServiceSignupWithPhoneNumberProcedure = "/auth.AuthService/SignupWithPhoneNumber"
	// AuthServiceVerifyPhoneNumberProcedure is the fully-qualified name of the AuthService's
	// VerifyPhoneNumber RPC.
	AuthServiceVerifyPhoneNumberProcedure = "/auth.AuthService/VerifyPhoneNumber"
	// AuthServiceLoginWithPhoneNumberProcedure is the fully-qualified name of the AuthService's
	// LoginWithPhoneNumber RPC.
	AuthServiceLoginWithPhoneNumberProcedure = "/auth.AuthService/LoginWithPhoneNumber"
	// AuthServiceValidatePhoneNumberLoginProcedure is the fully-qualified name of the AuthService's
	// ValidatePhoneNumberLogin RPC.
	AuthServiceValidatePhoneNumberLoginProcedure = "/auth.AuthService/ValidatePhoneNumberLogin"
	// AuthServiceGetProfileProcedure is the fully-qualified name of the AuthService's GetProfile RPC.
	AuthServiceGetProfileProcedure = "/auth.AuthService/GetProfile"
)

// AuthServiceClient is a client for the auth.AuthService service.
type AuthServiceClient interface {
	SignupWithPhoneNumber(context.Context, *connect_go.Request[protobufs.SignupRequest]) (*connect_go.Response[protobufs.SignupResponse], error)
	VerifyPhoneNumber(context.Context, *connect_go.Request[protobufs.VerifyRequest]) (*connect_go.Response[protobufs.VerifyResponse], error)
	LoginWithPhoneNumber(context.Context, *connect_go.Request[protobufs.LoginRequest]) (*connect_go.Response[protobufs.LoginResponse], error)
	ValidatePhoneNumberLogin(context.Context, *connect_go.Request[protobufs.ValidatePhoneNumberRequest]) (*connect_go.Response[protobufs.ValidatePhoneNumberResponse], error)
	GetProfile(context.Context, *connect_go.Request[protobufs.ProfileRequest]) (*connect_go.Response[protobufs.ProfileResponse], error)
}

// NewAuthServiceClient constructs a client for the auth.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &authServiceClient{
		signupWithPhoneNumber: connect_go.NewClient[protobufs.SignupRequest, protobufs.SignupResponse](
			httpClient,
			baseURL+AuthServiceSignupWithPhoneNumberProcedure,
			opts...,
		),
		verifyPhoneNumber: connect_go.NewClient[protobufs.VerifyRequest, protobufs.VerifyResponse](
			httpClient,
			baseURL+AuthServiceVerifyPhoneNumberProcedure,
			opts...,
		),
		loginWithPhoneNumber: connect_go.NewClient[protobufs.LoginRequest, protobufs.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginWithPhoneNumberProcedure,
			opts...,
		),
		validatePhoneNumberLogin: connect_go.NewClient[protobufs.ValidatePhoneNumberRequest, protobufs.ValidatePhoneNumberResponse](
			httpClient,
			baseURL+AuthServiceValidatePhoneNumberLoginProcedure,
			opts...,
		),
		getProfile: connect_go.NewClient[protobufs.ProfileRequest, protobufs.ProfileResponse](
			httpClient,
			baseURL+AuthServiceGetProfileProcedure,
			opts...,
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	signupWithPhoneNumber    *connect_go.Client[protobufs.SignupRequest, protobufs.SignupResponse]
	verifyPhoneNumber        *connect_go.Client[protobufs.VerifyRequest, protobufs.VerifyResponse]
	loginWithPhoneNumber     *connect_go.Client[protobufs.LoginRequest, protobufs.LoginResponse]
	validatePhoneNumberLogin *connect_go.Client[protobufs.ValidatePhoneNumberRequest, protobufs.ValidatePhoneNumberResponse]
	getProfile               *connect_go.Client[protobufs.ProfileRequest, protobufs.ProfileResponse]
}

// SignupWithPhoneNumber calls auth.AuthService.SignupWithPhoneNumber.
func (c *authServiceClient) SignupWithPhoneNumber(ctx context.Context, req *connect_go.Request[protobufs.SignupRequest]) (*connect_go.Response[protobufs.SignupResponse], error) {
	return c.signupWithPhoneNumber.CallUnary(ctx, req)
}

// VerifyPhoneNumber calls auth.AuthService.VerifyPhoneNumber.
func (c *authServiceClient) VerifyPhoneNumber(ctx context.Context, req *connect_go.Request[protobufs.VerifyRequest]) (*connect_go.Response[protobufs.VerifyResponse], error) {
	return c.verifyPhoneNumber.CallUnary(ctx, req)
}

// LoginWithPhoneNumber calls auth.AuthService.LoginWithPhoneNumber.
func (c *authServiceClient) LoginWithPhoneNumber(ctx context.Context, req *connect_go.Request[protobufs.LoginRequest]) (*connect_go.Response[protobufs.LoginResponse], error) {
	return c.loginWithPhoneNumber.CallUnary(ctx, req)
}

// ValidatePhoneNumberLogin calls auth.AuthService.ValidatePhoneNumberLogin.
func (c *authServiceClient) ValidatePhoneNumberLogin(ctx context.Context, req *connect_go.Request[protobufs.ValidatePhoneNumberRequest]) (*connect_go.Response[protobufs.ValidatePhoneNumberResponse], error) {
	return c.validatePhoneNumberLogin.CallUnary(ctx, req)
}

// GetProfile calls auth.AuthService.GetProfile.
func (c *authServiceClient) GetProfile(ctx context.Context, req *connect_go.Request[protobufs.ProfileRequest]) (*connect_go.Response[protobufs.ProfileResponse], error) {
	return c.getProfile.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the auth.AuthService service.
type AuthServiceHandler interface {
	SignupWithPhoneNumber(context.Context, *connect_go.Request[protobufs.SignupRequest]) (*connect_go.Response[protobufs.SignupResponse], error)
	VerifyPhoneNumber(context.Context, *connect_go.Request[protobufs.VerifyRequest]) (*connect_go.Response[protobufs.VerifyResponse], error)
	LoginWithPhoneNumber(context.Context, *connect_go.Request[protobufs.LoginRequest]) (*connect_go.Response[protobufs.LoginResponse], error)
	ValidatePhoneNumberLogin(context.Context, *connect_go.Request[protobufs.ValidatePhoneNumberRequest]) (*connect_go.Response[protobufs.ValidatePhoneNumberResponse], error)
	GetProfile(context.Context, *connect_go.Request[protobufs.ProfileRequest]) (*connect_go.Response[protobufs.ProfileResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	authServiceSignupWithPhoneNumberHandler := connect_go.NewUnaryHandler(
		AuthServiceSignupWithPhoneNumberProcedure,
		svc.SignupWithPhoneNumber,
		opts...,
	)
	authServiceVerifyPhoneNumberHandler := connect_go.NewUnaryHandler(
		AuthServiceVerifyPhoneNumberProcedure,
		svc.VerifyPhoneNumber,
		opts...,
	)
	authServiceLoginWithPhoneNumberHandler := connect_go.NewUnaryHandler(
		AuthServiceLoginWithPhoneNumberProcedure,
		svc.LoginWithPhoneNumber,
		opts...,
	)
	authServiceValidatePhoneNumberLoginHandler := connect_go.NewUnaryHandler(
		AuthServiceValidatePhoneNumberLoginProcedure,
		svc.ValidatePhoneNumberLogin,
		opts...,
	)
	authServiceGetProfileHandler := connect_go.NewUnaryHandler(
		AuthServiceGetProfileProcedure,
		svc.GetProfile,
		opts...,
	)
	return "/auth.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceSignupWithPhoneNumberProcedure:
			authServiceSignupWithPhoneNumberHandler.ServeHTTP(w, r)
		case AuthServiceVerifyPhoneNumberProcedure:
			authServiceVerifyPhoneNumberHandler.ServeHTTP(w, r)
		case AuthServiceLoginWithPhoneNumberProcedure:
			authServiceLoginWithPhoneNumberHandler.ServeHTTP(w, r)
		case AuthServiceValidatePhoneNumberLoginProcedure:
			authServiceValidatePhoneNumberLoginHandler.ServeHTTP(w, r)
		case AuthServiceGetProfileProcedure:
			authServiceGetProfileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) SignupWithPhoneNumber(context.Context, *connect_go.Request[protobufs.SignupRequest]) (*connect_go.Response[protobufs.SignupResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("auth.AuthService.SignupWithPhoneNumber is not implemented"))
}

func (UnimplementedAuthServiceHandler) VerifyPhoneNumber(context.Context, *connect_go.Request[protobufs.VerifyRequest]) (*connect_go.Response[protobufs.VerifyResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("auth.AuthService.VerifyPhoneNumber is not implemented"))
}

func (UnimplementedAuthServiceHandler) LoginWithPhoneNumber(context.Context, *connect_go.Request[protobufs.LoginRequest]) (*connect_go.Response[protobufs.LoginResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("auth.AuthService.LoginWithPhoneNumber is not implemented"))
}

func (UnimplementedAuthServiceHandler) ValidatePhoneNumberLogin(context.Context, *connect_go.Request[protobufs.ValidatePhoneNumberRequest]) (*connect_go.Response[protobufs.ValidatePhoneNumberResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("auth.AuthService.ValidatePhoneNumberLogin is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetProfile(context.Context, *connect_go.Request[protobufs.ProfileRequest]) (*connect_go.Response[protobufs.ProfileResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("auth.AuthService.GetProfile is not implemented"))
}
